server:
  port: 2222
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/

# ${server.port}为该服务的端口号
  instance:
    status-page-url: http://localhost:${server.port}/swagger-ui.html
spring:
  application:
    name: Test1-service
  boot:
    admin:
      url: http://localhost:1112
  zipkin:
    base-url: http://localhost:1114
management:  
  security:  
    enabled: false